name = "GLM Latest"
release_date = "2026-06-26"
last_updated = "2026-06-26"
attachment = false
reasoning = true
tool_call = true
open_weights = false
temperature = true
structured_output = true

[limit]
context = 1_024_000
output = 4_096

[modalities]
input = ["text"]
output = ["text"]
